---
# PC
#routing-mark: 6666
interface-name: wlan0
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - 0.0.0.0:53
#    - 8.8.8.8:53
#    - tcp://8.8.8.8:53
  auto-route: true # auto set global route
    #  auto-detect-interface: true # conflict with interface-name
####
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "./dashboard/clash-dashboard/"
unified-delay: true
dns:
  enable: true
  use-hosts: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:6868
  nameserver:
    - https://dns.cloudflare.com/dns-query
  ipv6: true
proxy-providers:
  Maps&Zoom:
    type: file
    path: "./proxy_provider/mapsandzoom.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 60
proxy-groups:
- name: "\U0001F511Proxy"
  type: select
  proxies:
  - "\U0001F525 Best Ping"
  use:
  - Maps&Zoom
- name: "\U0001F525 Best Ping"
  type: url-test
  proxies:
  use:
  - Maps&Zoom
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: DNS
  type: url-test
  use:
    - Maps&Zoom
  proxies:
    - DIRECT
  url: http://cp.cloudflare.com
  interval: 180
  lazy: true
- name: AdBlock
  type: select
  proxies:
  - "\U0001F511Proxy"
  - REJECT
  - DIRECT
- name: "\U0001F3AFOthers"
  type: select
  proxies:
  - "\U0001F511Proxy"
  - DIRECT
rules:
- DOMAIN-KEYWORD,announce,DIRECT,no-resolve
- DOMAIN-KEYWORD,torrent,DIRECT,no-resolve
- DOMAIN-KEYWORD,tracker,DIRECT,no-resolve
- DOMAIN-SUFFIX,smtp,DIRECT,no-resolve
- DOMAIN-SUFFIX,local,DIRECT,no-resolve
- IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
- IP-CIDR,192.168.8.0/24,DIRECT,no-resolve
- IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
- IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
- IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
- IP-CIDR6,::1/128,DIRECT,no-resolve
- IP-CIDR6,fc00::/7,DIRECT,no-resolve
- IP-CIDR6,fe80::/10,DIRECT,no-resolve
- IP-CIDR6,fd00::/8,DIRECT,no-resolve
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,AdBlock,AdBlock
- "MATCH,\U0001F3AFOthers"
rule-providers:
  AdBlock:
    type: file
    behavior: classical
    path: "./rule_provider/❌AdBlock.yaml"
    interval: 86400
profile:
  store-selected: true
